server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**

        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
